### ISSUE TITLE
Checkout multiple products??

### ISSUE THREAD

**Issue by susonwaiba** [khalti/khalti-sdk-web#12]
I was checking out your web js sdk and it seems that we have no options for multiple checkout system??
and quick question; will there be Magento extension also coming soon?

**Comment by poudel** [comment]
Multiple checkout should be possible by dynamically instantiating the `KhaltiCheckout` object.

For example, something like this:

```javascript
function showCheckout(config, productId, price) {
        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById(`payment-button-${productId}`);
        btn.onclick = function () {
            checkout.show({amount: price});
        }
        return checkout;
}
```

Please let us know if you encounter any issue.

**Comment by susonwaiba** [comment]
@poudel I am talking about checking out multiple products at once. Like I have 5 products in my cart. and I want to check out at once. I checked khalti woocommerce implementation where there was no product information passed. Is it the way to do it or it will get changed in future.?

**Comment by acpmasquerade** [comment]
Product information is optional. It's basically for the reporting purpose, so that the merchant and use the information for any dispute handling, reporting etc.

If you would like to make single payment for multiple products, simply add only one checkout / pay button. Provide the amount to be charged as the total amount. If you still need the product information, you can create a comma separated list of product names.

**Comment by susonwaiba** [comment]
ah.. so, basically as woocommerce implementation.  Thanks @acpmasquerade
